### ISSUE TITLE
Insufficient readme

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [quartata/cinnamon-gum#1]
The lack of readme is... disturbing. Please fix ASAP

**Comment by quartata** [comment]
1. I just made this repo how do you already know about it
2. ok

**Comment by ConorOBrien-Foxx** [comment]
I follow you on github :P not being on PPCG for another 4+ hours more makes me want to catch up here :P :P :P

**Comment by RikerW** [comment]
-1 still has pretty hecking small readme
